### PR TITLE
Home

### PR DESCRIPTION
**Pull request by ElvisGT**

### CODE REVIEW

**Review by JancoBH — CHANGES_REQUESTED** [review]
It doesn't make sense to merge something that we won't use in the future, otherwise, you are using the same Button.tsx code that is in PR #4

**Comment by ElvisGT** [comment]
wainting for a new review

**Review by JancoBH — CHANGES_REQUESTED** [review]
You need to modify your button component.

🛑 The button component can't grow on width size.
🛑 You can't implement different elements like icons or images.
🛑 The button needs to have padding on the "x" direction and all its elements have to be in the same line (you can use display flex with aligning and justify center).

Check discord, I solved it for you but you can still improve it and have a better version 👍

**Review by JancoBH — CHANGES_REQUESTED** [review]
🛑 change name to type.
🛑  The button component has to have internal CSS classes, the idea is to not remember all classes outside and in the index.tsx example you wrote the CSS classes outside the component and it has to be inside the button.

**Review by JancoBH — APPROVED** [review]

**Pull request merged**
